Repository arunkumar9t2/scabbard, pull requests merged in 2022-10, with the labels that each got.

#115 Update README.md
  README.md
Labels: enhancement

#118 Update lint job to run `apiCheck`
  .github/workflows/ci.yml
Labels: enhancement

#120 Setup Kodiak
  .kodiak.toml
Labels: automerge

#119 Fix opt in deprecation
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/kt/KotlinCommon.kt
Labels: enhancement, tech-debt, automerge
